-- require('core.plugin_config.nvim-tree')
require('core.plugin_config.telescope')
require('core.plugin_config.nvim-treesitter')
require('core.plugin_config.lspconfig')
require('core.plugin_config.comment')
require('core.plugin_config.catppuccin')
require('core.plugin_config.autocompletion')
require('core.plugin_config.null-ls')
require('core.plugin_config.prettier')
require('core.plugin_config.gitsigns')
require('core.plugin_config.lualine')
require('core.plugin_config.noice')
require('core.plugin_config.toggleTerm')
require('core.plugin_config.ayu')
require('core.plugin_config.lspkind')
require('core.plugin_config.lspsaga')
